/*
 * Visa API
 *
 * This is a quick Swagger Spec for the Visa API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package visa

type Body struct {
	//SearchAttrList Merchantsearchv1searchSearchAttrList `json:"searchAttrList,omitempty"`
	SearchAttrList MerchantSearchAttrList `json:"searchAttrList,omitempty"`

	ResponseAttrList []string `json:"responseAttrList,omitempty"`

	//SearchOptions Merchantsearchv1searchSearchOptions `json:"searchOptions,omitempty"`
	SearchOptions MerchantSearchOptions `json:"searchOptions,omitempty"`

	//Header Merchantsearchv1searchHeader `json:"header,omitempty"`
	Header MerchantSearchHeader `json:"header,omitempty"`
}
