/*
 * Visa API
 *
 * This is a quick Swagger Spec for the Visa API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package visa

type MerchantSearchAttrList struct {

	// Name of the Merchant or Supplier. Note: Optional when any one of VisaMerchantId or VisaStoreId or BusinessRegistrationId or MerchantUrl or AcquirerCardAcceptorId is provided.
	MerchantName string `json:"merchantName,omitempty"`

	// Double, max: 8 characters. Unique identifier for Merchant provided by VISA. Note: Optional when any one of MerchantName or VisaStoreId or BusinessRegistrationId or MerchantUrl or AcquirerCardAcceptorId is provided.
	VisaMerchantId string `json:"visaMerchantId,omitempty"`

	// Double, max: 9 characters. Unique identifier for a Branch/Outlet. Note: Optional when any one of MerchantName or VisaMerchantId or BusinessRegistrationId or MerchantUrl or AcquirerCardAcceptorId is provided.
	VisaStoreId string `json:"visaStoreId,omitempty"`

	// Merchants Business Registration ID/Tax ID.Note: Optional when any one of MerchantName or VisaMerchantId or VisaStoreId or MerchantUrl or AcquirerCardAcceptorId is provided.
	BusinessRegistrationId string `json:"businessRegistrationId,omitempty"`

	// Address of the registered Merchant
	MerchantStreetAddress string `json:"merchantStreetAddress,omitempty"`

	// City of the registered Merchant
	MerchantCity string `json:"merchantCity,omitempty"`

	// Alpha, max: 2 characters. State of the registered Merchant. Ex: US
	MerchantState string `json:"merchantState,omitempty"`

	// Postal Code of the registered Merchant
	MerchantPostalCode string `json:"merchantPostalCode,omitempty"`

	MerchantCountryCode string `json:"merchantCountryCode,omitempty"`
}
