/*
 * Visa API
 *
 * This is a quick Swagger Spec for the Visa API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package visa

type MerchantSearchOptions struct {

	// * and ?/Wildcard Tag. Allows user to search on Merchant Name using wildcards
	WildCard []string `json:"wildCard,omitempty"`

	// Allows user to define maximum number of records to be sent in the response. If the User doesn’t set the maxRecords the value will be set by default to 25. Note: Response records will be unique and sent in order of highest to lowest Match Score
	MaxRecords int `json:"maxRecords,omitempty"`

	// Allows user to define if they would like to see which request attributes found a matching record
	MatchIndicators bool `json:"matchIndicators,omitempty"`

	// Allows user to define if they would like to see the matchScore and receive the response in order of MatchScore
	MatchScore bool `json:"matchScore,omitempty"`

	// Proximity tag. Allows user to do a proximity search on Merchant Name (upto 1 spaces). Note: Proximity Search cannot be combined with Wildcard. If wildcards are used proximity will be ignored.
	Proximity []string `json:"proximity,omitempty"`
}
