/*
 * Visa API
 *
 * This is a quick Swagger Spec for the Visa API
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package visa

import (
	"github.com/grokify/mogo/time/timeutil"
)

type MerchantSearchHeader struct {

	// max: 50 characters. A string which uniquely identifies the service request. Requesting application need to create this unique message Id
	RequestMessageId string `json:"requestMessageId,omitempty"`

	// Optional. Integer Default='0'. Records displayed start at the defined number (Defaulted to 0 if not provided in request)
	StartIndex int `json:"startIndex,omitempty"`

	// YYYY-MM-DDThh:mm:ss.sss, max: 23 characters. Date and time at which Request is sent (up to milliseconds in UTC). Ex: 2008-09-19T00:00:00.000
	MessageDateTime timeutil.ISO8601NoTzMilliTime `json:"messageDateTime,omitempty"`
}
