/* 
 * Visa API
 *
 * This is a quick Swagger Spec for the Visa API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package visa

type MerchantSearchRequest struct {

	SearchAttrList MerchantSearchAttrList `json:"searchAttrList,omitempty"`

	ResponseAttrList []string `json:"responseAttrList,omitempty"`

	SearchOptions MerchantSearchOptions `json:"searchOptions,omitempty"`

	Header MerchantSearchHeader `json:"header,omitempty"`
}
