/* 
 * Visa API
 *
 * This is a quick Swagger Spec for the Visa API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package visa

import (
	"time"
)

type ResponseHeader struct {

	// A string uniquely identifies the service request. Response will contain same Message Id as received from requesting application
	RequestMessageId string `json:"requestMessageId,omitempty"`

	// Date and time at which Response is sent (up to milliseconds in UTC). Ex: 2008-09-19T00:00:00.000
	MessageDateTime time.Time `json:"messageDateTime,omitempty"`

	// A combination of Service Id, Application Id, an Integer and current Timestamp that uniquely identifies the current request-response processing
	ResponseMessageId string `json:"responseMessageId,omitempty"`

	// Record Start Index
	StartIndex string `json:"startIndex,omitempty"`

	// Record End Index
	EndIndex string `json:"endIndex,omitempty"`

	// Number of records matched
	NumRecordsMatched int32 `json:"numRecordsMatched,omitempty"`

	// Number of records returned. Note: Matched records may differ from returned records if Max Records is defined or system limit is exceeded
	NumRecordsReturned int32 `json:"numRecordsReturned,omitempty"`
}
