/* 
 * Visa API
 *
 * This is a quick Swagger Spec for the Visa API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package visa

type ResponseStatus struct {

	// List of attributes that found a match or did not find a match
	StatusCode string `json:"statusCode,omitempty"`

	// A description of the StatusCode. A brief description indicating the result of the Service Request
	StatusDescription string `json:"statusDescription,omitempty"`
}
